jobs:
  build:
    name: SerDe Test
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout
      uses: actions/checkout@v3
    - continue-on-error: true
      name: Checkout C++
      uses: actions/checkout@v3
      with:
        path: cpp
        repository: apache/datasketches-cpp
    - continue-on-error: true
      name: Configure C++ build
      run: cd cpp/build && cmake .. -DGENERATE=true
    - continue-on-error: true
      name: Build C++ unit tests
      run: cd cpp && cmake --build build --config Release
    - continue-on-error: true
      name: Run C++ tests
      run: cd cpp && cmake --build build --config Release --target test
    - continue-on-error: true
      name: Make dir
      run: mkdir -p serialization_test_data/cpp_generated_files
    - continue-on-error: true
      name: Copy files
      run: cp cpp/build/*/test/*_cpp.sk serialization_test_data/cpp_generated_files
    - continue-on-error: true
      name: Run Java tests
      run: mvn test -P check-cpp-files
name: Serialization Compatibility Test
on:
  repository_dispatch:
    types: trigger-ga___check_cpp_files.yml
