env:
  MAVEN_OPTS: -Xmx4g -Xms1g
jobs:
  build:
    env:
      JDK_VERSION: ${{ matrix.jdk }}
    name: Build, Test, Coverage
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout ${{ github.ref }} ( ${{ github.sha }} )
      uses: actions/checkout@v3
      with:
        persist-credentials: false
    - continue-on-error: true
      name: Cache local Maven repository
      uses: actions/cache@v3
      with:
        key: build-${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        path: ~/.m2/repository
        restore-keys: build-${{ runner.os }}-maven-
    - continue-on-error: true
      name: Install Matrix JDK
      uses: actions/setup-java@v3
      with:
        architecture: x64
        distribution: temurin
        java-package: jdk
        java-version: ${{ matrix.jdk }}
    - continue-on-error: true
      name: Echo Java Version
      run: 'java -version

        '
    - continue-on-error: true
      if: ${{ matrix.jdk == 8 && success() }}
      name: Test, Package, Verify, Coverage Report
      run: mvn verify coveralls:report -B -DrepoToken=${{secrets.coveralls_token}}
        ${{matrix.os.skip_javadoc}} ${{matrix.os.skip_gpg}}
    strategy:
      fail-fast: false
      matrix:
        include:
        - os: ubuntu-latest
          skip_gpg: -Dgpg.skip=true
          skip_javadoc: -Dmaven.javadoc.skip=true
        jdk:
        - 8
        os:
        - ubuntu-latest
name: Datasketches-Java Manual Coverage Report
on:
  repository_dispatch:
    types: trigger-ga___manual-coverage.yml
