env:
  MAVEN_OPTS: -Xmx4g -Xms1g
jobs:
  build:
    env:
      JDK_VERSION: ${{ matrix.jdk }}
    name: Build, Test, Install
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout ${{ github.ref }} ( ${{ github.sha }} )
      uses: actions/checkout@v3
      with:
        persist-credentials: false
    - continue-on-error: true
      name: Cache local Maven repository
      uses: actions/cache@v3
      with:
        key: build-${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        path: ~/.m2/repository
        restore-keys: build-${{ runner.os }}-maven-
    - continue-on-error: true
      name: Install Matrix JDK
      uses: actions/setup-java@v3
      with:
        architecture: x64
        distribution: temurin
        java-package: jdk
        java-version: ${{ matrix.jdk }}
    - continue-on-error: true
      name: Echo Java Version
      run: 'java -version

        '
    - continue-on-error: true
      name: Test
      run: 'mvn clean test ${{matrix.os.skip_javadoc}} ${{matrix.os.skip_gpg}}

        '
    - continue-on-error: true
      name: Install
      run: 'mvn clean install -B ${{matrix.os.skip_javadoc}} -D skipTests=true ${{matrix.os.skip_gpg}}

        '
    strategy:
      fail-fast: false
      matrix:
        include:
        - os: windows-latest
          skip_gpg: '`-Dgpg`.skip=true'
          skip_javadoc: '`-Dmaven`.javadoc`.skip=true'
        - os: ubuntu-latest
          skip_gpg: -Dgpg.skip=true
          skip_javadoc: -Dmaven.javadoc.skip=true
        - os: macos-latest
          skip_gpg: -Dgpg.skip=true
          skip_javadoc: -Dmaven.javadoc.skip=true
        jdk:
        - 8
        - 11
        os:
        - windows-latest
        - ubuntu-latest
        - macos-latest
name: DataSketches-Java Manual OS Matrix Test & Install
on:
  repository_dispatch:
    types: trigger-ga___manual-os-matrix.yml
